//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.22 at 12:44:28 PM CEST 
//


package sistematica.aggregatore.ws.rest.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for location_referenceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="location_referenceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="tmc_info" type="{http://www.5t.torino.it/simone/ns/traffic_data}tmcType"/>
 *         &lt;element name="detailed_graph_info">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{http://www.5t.torino.it/simone/ns/traffic_data}detailedGraphType">
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="WGS84_info" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "location_referenceType", propOrder = {
    "tmcInfo",
    "detailedGraphInfo",
    "wgs84Info"
})
public class LocationReferenceType {

    @XmlElement(name = "tmc_info")
    protected TmcType tmcInfo;
    @XmlElement(name = "detailed_graph_info")
    protected LocationReferenceType.DetailedGraphInfo detailedGraphInfo;
    @XmlElement(name = "WGS84_info")
    protected Object wgs84Info;

    /**
     * Gets the value of the tmcInfo property.
     * 
     * @return
     *     possible object is
     *     {@link TmcType }
     *     
     */
    public TmcType getTmcInfo() {
        return tmcInfo;
    }

    /**
     * Sets the value of the tmcInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link TmcType }
     *     
     */
    public void setTmcInfo(TmcType value) {
        this.tmcInfo = value;
    }

    /**
     * Gets the value of the detailedGraphInfo property.
     * 
     * @return
     *     possible object is
     *     {@link LocationReferenceType.DetailedGraphInfo }
     *     
     */
    public LocationReferenceType.DetailedGraphInfo getDetailedGraphInfo() {
        return detailedGraphInfo;
    }

    /**
     * Sets the value of the detailedGraphInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocationReferenceType.DetailedGraphInfo }
     *     
     */
    public void setDetailedGraphInfo(LocationReferenceType.DetailedGraphInfo value) {
        this.detailedGraphInfo = value;
    }

    /**
     * Gets the value of the wgs84Info property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getWGS84Info() {
        return wgs84Info;
    }

    /**
     * Sets the value of the wgs84Info property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setWGS84Info(Object value) {
        this.wgs84Info = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{http://www.5t.torino.it/simone/ns/traffic_data}detailedGraphType">
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class DetailedGraphInfo
        extends DetailedGraphType
    {


    }

}
