//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.22 at 12:44:28 PM CEST 
//


package sistematica.aggregatore.ws.rest.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the it.torino._5t.simone.ns.traffic_data package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: it.torino._5t.simone.ns.traffic_data
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ODprofiledType }
     * 
     */
    public ODprofiledType createODprofiledType() {
        return new ODprofiledType();
    }

    /**
     * Create an instance of {@link SpeedFlowType }
     * 
     */
    public SpeedFlowType createSpeedFlowType() {
        return new SpeedFlowType();
    }

    /**
     * Create an instance of {@link MRDDataType }
     * 
     */
    public MRDDataType createMRDDataType() {
        return new MRDDataType();
    }

    /**
     * Create an instance of {@link LocationReferenceType }
     * 
     */
    public LocationReferenceType createLocationReferenceType() {
        return new LocationReferenceType();
    }

    /**
     * Create an instance of {@link TTType }
     * 
     */
    public TTType createTTType() {
        return new TTType();
    }

    /**
     * Create an instance of {@link DetailedGraphType }
     * 
     */
    public DetailedGraphType createDetailedGraphType() {
        return new DetailedGraphType();
    }

    /**
     * Create an instance of {@link PKType }
     * 
     */
    public PKType createPKType() {
        return new PKType();
    }

    /**
     * Create an instance of {@link TTprofiledType }
     * 
     */
    public TTprofiledType createTTprofiledType() {
        return new TTprofiledType();
    }

    /**
     * Create an instance of {@link FDTType }
     * 
     */
    public FDTType createFDTType() {
        return new FDTType();
    }

    /**
     * Create an instance of {@link LocationReferenceType.DetailedGraphInfo }
     * 
     */
    public LocationReferenceType.DetailedGraphInfo createLocationReferenceTypeDetailedGraphInfo() {
        return new LocationReferenceType.DetailedGraphInfo();
    }

    /**
     * Create an instance of {@link RDDataType }
     * 
     */
    public RDDataType createRDDataType() {
        return new RDDataType();
    }

    /**
     * Create an instance of {@link TrafficData }
     * 
     */
    public TrafficData createTrafficData() {
        return new TrafficData();
    }

    /**
     * Create an instance of {@link ODType }
     * 
     */
    public ODType createODType() {
        return new ODType();
    }

    /**
     * Create an instance of {@link TrafficData.FDTData }
     * 
     */
    public TrafficData.FDTData createTrafficDataFDTData() {
        return new TrafficData.FDTData();
    }

    /**
     * Create an instance of {@link TmcType }
     * 
     */
    public TmcType createTmcType() {
        return new TmcType();
    }

}
