//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.22 at 12:44:28 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.5t.torino.it/simone/ns/traffic_data", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package sistematica.aggregatore.ws.rest.jaxb;
