//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.22 at 12:44:28 PM CEST 
//


package sistematica.aggregatore.ws.rest.jaxb;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for RD_dataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RD_dataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="veh" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="timestamp" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="lat" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="lng" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="alt" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="bearing" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="speed" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="hdop" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="tracking_distance" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="global_distance" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="event" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="sampling"/>
 *             &lt;enumeration value="keyon"/>
 *             &lt;enumeration value="keyoff"/>
 *             &lt;enumeration value="dooropened"/>
 *             &lt;enumeration value="doorclosed"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="tracking_type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="vehicle_type" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="AU"/>
 *             &lt;enumeration value="VC"/>
 *             &lt;enumeration value="VP"/>
 *             &lt;enumeration value="TX"/>
 *             &lt;enumeration value="MPU"/>
 *             &lt;enumeration value="MPE"/>
 *             &lt;enumeration value="MTR"/>
 *             &lt;enumeration value="BUS"/>
 *             &lt;enumeration value="MSP"/>
 *             &lt;enumeration value="M"/>
 *             &lt;enumeration value="M1"/>
 *             &lt;enumeration value="M2"/>
 *             &lt;enumeration value="M3"/>
 *             &lt;enumeration value="N"/>
 *             &lt;enumeration value="N1"/>
 *             &lt;enumeration value="N2"/>
 *             &lt;enumeration value="N3"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="vehicle_information" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RD_dataType")
@XmlSeeAlso({
    MRDDataType.class
})
public class RDDataType {

    @XmlAttribute(required = true)
    protected String veh;
    @XmlAttribute(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar timestamp;
    @XmlAttribute(required = true)
    protected BigDecimal lat;
    @XmlAttribute(required = true)
    protected BigDecimal lng;
    @XmlAttribute
    protected BigDecimal alt;
    @XmlAttribute
    protected BigDecimal bearing;
    @XmlAttribute
    protected BigDecimal speed;
    @XmlAttribute
    protected BigDecimal hdop;
    @XmlAttribute(name = "tracking_distance")
    protected BigDecimal trackingDistance;
    @XmlAttribute(name = "global_distance")
    protected BigDecimal globalDistance;
    @XmlAttribute(required = true)
    protected String event;
    @XmlAttribute(name = "tracking_type")
    protected String trackingType;
    @XmlAttribute(name = "vehicle_type", required = true)
    protected String vehicleType;
    @XmlAttribute(name = "vehicle_information")
    protected String vehicleInformation;

    /**
     * Gets the value of the veh property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVeh() {
        return veh;
    }

    /**
     * Sets the value of the veh property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVeh(String value) {
        this.veh = value;
    }

    /**
     * Gets the value of the timestamp property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTimestamp() {
        return timestamp;
    }

    /**
     * Sets the value of the timestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTimestamp(XMLGregorianCalendar value) {
        this.timestamp = value;
    }

    /**
     * Gets the value of the lat property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLat() {
        return lat;
    }

    /**
     * Sets the value of the lat property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLat(BigDecimal value) {
        this.lat = value;
    }

    /**
     * Gets the value of the lng property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLng() {
        return lng;
    }

    /**
     * Sets the value of the lng property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLng(BigDecimal value) {
        this.lng = value;
    }

    /**
     * Gets the value of the alt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAlt() {
        return alt;
    }

    /**
     * Sets the value of the alt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAlt(BigDecimal value) {
        this.alt = value;
    }

    /**
     * Gets the value of the bearing property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getBearing() {
        return bearing;
    }

    /**
     * Sets the value of the bearing property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setBearing(BigDecimal value) {
        this.bearing = value;
    }

    /**
     * Gets the value of the speed property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSpeed() {
        return speed;
    }

    /**
     * Sets the value of the speed property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSpeed(BigDecimal value) {
        this.speed = value;
    }

    /**
     * Gets the value of the hdop property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getHdop() {
        return hdop;
    }

    /**
     * Sets the value of the hdop property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setHdop(BigDecimal value) {
        this.hdop = value;
    }

    /**
     * Gets the value of the trackingDistance property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTrackingDistance() {
        return trackingDistance;
    }

    /**
     * Sets the value of the trackingDistance property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTrackingDistance(BigDecimal value) {
        this.trackingDistance = value;
    }

    /**
     * Gets the value of the globalDistance property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getGlobalDistance() {
        return globalDistance;
    }

    /**
     * Sets the value of the globalDistance property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setGlobalDistance(BigDecimal value) {
        this.globalDistance = value;
    }

    /**
     * Gets the value of the event property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEvent() {
        return event;
    }

    /**
     * Sets the value of the event property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEvent(String value) {
        this.event = value;
    }

    /**
     * Gets the value of the trackingType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrackingType() {
        return trackingType;
    }

    /**
     * Sets the value of the trackingType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrackingType(String value) {
        this.trackingType = value;
    }

    /**
     * Gets the value of the vehicleType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVehicleType() {
        return vehicleType;
    }

    /**
     * Sets the value of the vehicleType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVehicleType(String value) {
        this.vehicleType = value;
    }

    /**
     * Gets the value of the vehicleInformation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVehicleInformation() {
        return vehicleInformation;
    }

    /**
     * Sets the value of the vehicleInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVehicleInformation(String value) {
        this.vehicleInformation = value;
    }

}
