//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.22 at 12:44:28 PM CEST 
//


package sistematica.aggregatore.ws.rest.jaxb;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tmcType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tmcType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="cid" type="{http://www.w3.org/2001/XMLSchema}integer" default="25" />
 *       &lt;attribute name="tabcd" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="locdb_ver" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tmcType")
public class TmcType {

    @XmlAttribute
    protected BigInteger cid;
    @XmlAttribute(required = true)
    protected BigInteger tabcd;
    @XmlAttribute(name = "locdb_ver")
    protected String locdbVer;

    /**
     * Gets the value of the cid property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCid() {
        if (cid == null) {
            return new BigInteger("25");
        } else {
            return cid;
        }
    }

    /**
     * Sets the value of the cid property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCid(BigInteger value) {
        this.cid = value;
    }

    /**
     * Gets the value of the tabcd property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTabcd() {
        return tabcd;
    }

    /**
     * Sets the value of the tabcd property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTabcd(BigInteger value) {
        this.tabcd = value;
    }

    /**
     * Gets the value of the locdbVer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocdbVer() {
        return locdbVer;
    }

    /**
     * Sets the value of the locdbVer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocdbVer(String value) {
        this.locdbVer = value;
    }

}
