//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.22 at 12:44:28 PM CEST 
//


package sistematica.aggregatore.ws.rest.jaxb;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Tratta stradale, delimitata da due location codes, per cui viene fornita la velocita' media ed il tempo di percorrenza. La sequenza (LCD1 - LCD2) determina il verso di percorrenza.
 * 
 * <p>Java class for TT_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TT_type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="lcd1" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="lcd2" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="len" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="time" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="speed" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="n_vehicles" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="std_dev" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="accuracy" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="estimated_speed" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="q_idx">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *             &lt;enumeration value="1"/>
 *             &lt;enumeration value="2"/>
 *             &lt;enumeration value="3"/>
 *             &lt;enumeration value="4"/>
 *             &lt;enumeration value="5"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="vehicle_type" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TT_type")
@XmlSeeAlso({
    TTprofiledType.class
})
public class TTType {

    @XmlAttribute(required = true)
    protected BigInteger lcd1;
    @XmlAttribute(required = true)
    protected BigInteger lcd2;
    @XmlAttribute
    protected BigDecimal len;
    @XmlAttribute(required = true)
    protected BigDecimal time;
    @XmlAttribute
    protected BigDecimal speed;
    @XmlAttribute(name = "n_vehicles")
    protected Integer nVehicles;
    @XmlAttribute(name = "std_dev")
    protected BigDecimal stdDev;
    @XmlAttribute
    protected Integer accuracy;
    @XmlAttribute(name = "estimated_speed")
    protected BigDecimal estimatedSpeed;
    @XmlAttribute(name = "q_idx")
    protected Integer qIdx;
    @XmlAttribute(name = "vehicle_type", required = true)
    protected String vehicleType;

    /**
     * Gets the value of the lcd1 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLcd1() {
        return lcd1;
    }

    /**
     * Sets the value of the lcd1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLcd1(BigInteger value) {
        this.lcd1 = value;
    }

    /**
     * Gets the value of the lcd2 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLcd2() {
        return lcd2;
    }

    /**
     * Sets the value of the lcd2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLcd2(BigInteger value) {
        this.lcd2 = value;
    }

    /**
     * Gets the value of the len property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLen() {
        return len;
    }

    /**
     * Sets the value of the len property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLen(BigDecimal value) {
        this.len = value;
    }

    /**
     * Gets the value of the time property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTime() {
        return time;
    }

    /**
     * Sets the value of the time property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTime(BigDecimal value) {
        this.time = value;
    }

    /**
     * Gets the value of the speed property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSpeed() {
        return speed;
    }

    /**
     * Sets the value of the speed property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSpeed(BigDecimal value) {
        this.speed = value;
    }

    /**
     * Gets the value of the nVehicles property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNVehicles() {
        return nVehicles;
    }

    /**
     * Sets the value of the nVehicles property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNVehicles(Integer value) {
        this.nVehicles = value;
    }

    /**
     * Gets the value of the stdDev property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getStdDev() {
        return stdDev;
    }

    /**
     * Sets the value of the stdDev property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setStdDev(BigDecimal value) {
        this.stdDev = value;
    }

    /**
     * Gets the value of the accuracy property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getAccuracy() {
        return accuracy;
    }

    /**
     * Sets the value of the accuracy property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setAccuracy(Integer value) {
        this.accuracy = value;
    }

    /**
     * Gets the value of the estimatedSpeed property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getEstimatedSpeed() {
        return estimatedSpeed;
    }

    /**
     * Sets the value of the estimatedSpeed property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setEstimatedSpeed(BigDecimal value) {
        this.estimatedSpeed = value;
    }

    /**
     * Gets the value of the qIdx property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getQIdx() {
        return qIdx;
    }

    /**
     * Sets the value of the qIdx property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setQIdx(Integer value) {
        this.qIdx = value;
    }

    /**
     * Gets the value of the vehicleType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVehicleType() {
        return vehicleType;
    }

    /**
     * Sets the value of the vehicleType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVehicleType(String value) {
        this.vehicleType = value;
    }

}
