CREATE TABLE IF NOT EXISTS `link` (
  `idno` int(11) NOT NULL DEFAULT '0',
  `tail` int(11) DEFAULT NULL,
  `head` int(11) DEFAULT NULL,
  `dirx` tinyint(4) DEFAULT '1',
  `name` varchar(255) DEFAULT '',
  `leng` double unsigned DEFAULT NULL,
  `netw` tinyint(4) DEFAULT '0',
  `conn` tinyint(4) DEFAULT '0',
  `ltyp` int(11) DEFAULT NULL,
  `ltnr` int(11) DEFAULT NULL,
  `hier` tinyint(3) unsigned DEFAULT '0',
  `proj` varchar(255) DEFAULT '',
  `dval` int(11) DEFAULT '0',
  `sped` double unsigned DEFAULT NULL,
  `itim` double unsigned DEFAULT NULL,
  `capa` double unsigned DEFAULT NULL,
  `nlan` int(11) DEFAULT NULL,
  `cycl` double unsigned DEFAULT NULL,
  `gren` double unsigned DEFAULT NULL,
  `bflw` double unsigned DEFAULT NULL,
  `jden` double unsigned DEFAULT NULL,
  `jwav` double unsigned DEFAULT NULL,
  `timf` int(11) DEFAULT NULL,
  `fund` int(11) DEFAULT NULL,
  `safe` int(11) DEFAULT NULL,
  `toll` double unsigned DEFAULT NULL,
  `gcst` double unsigned DEFAULT NULL,
  `sped_nr` double unsigned DEFAULT NULL,
  `itim_nr` double unsigned DEFAULT NULL,
  `capa_nr` double unsigned DEFAULT NULL,
  `nlan_nr` int(11) DEFAULT NULL,
  `cycl_nr` double unsigned DEFAULT NULL,
  `gren_nr` double unsigned DEFAULT NULL,
  `bflw_nr` double unsigned DEFAULT NULL,
  `jden_nr` double unsigned DEFAULT NULL,
  `jwav_nr` double unsigned DEFAULT NULL,
  `timf_nr` int(11) DEFAULT NULL,
  `fund_nr` int(11) DEFAULT NULL,
  `safe_nr` int(11) DEFAULT NULL,
  `toll_nr` double unsigned DEFAULT NULL,
  `gcst_nr` double unsigned DEFAULT NULL,
  `shap` multilinestring NOT NULL,
  PRIMARY KEY (`idno`),
  KEY `tail` (`tail`),
  KEY `head` (`head`),
  KEY `ltyp` (`ltyp`),
  KEY `ltnr` (`ltnr`),
  KEY `dval` (`dval`),
  KEY `timf` (`timf`),
  KEY `fund` (`fund`),
  KEY `safe` (`safe`),
  KEY `timf_nr` (`timf_nr`),
  KEY `fund_nr` (`fund_nr`),
  KEY `safe_nr` (`safe_nr`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
