CREATE TABLE `strt` (
  `idno` int(11) NOT NULL DEFAULT '0',
  `tail` int(11) DEFAULT NULL,
  `head` int(11) DEFAULT NULL,
  `dirx` tinyint(4) DEFAULT '1',
  `name` varchar(255) DEFAULT '',
  `leng` double unsigned DEFAULT NULL,
  `hier` tinyint(3) unsigned DEFAULT '0',
  `dval` int(11) DEFAULT '0',
  `sped` double unsigned DEFAULT NULL,
  `itim` double unsigned DEFAULT NULL,
  `cycl` double unsigned DEFAULT NULL,
  `gren` double unsigned DEFAULT NULL,
  `toll` double unsigned DEFAULT NULL,
  `gcst` double unsigned DEFAULT NULL,
  `sped_nr` double unsigned DEFAULT NULL,
  `itim_nr` double unsigned DEFAULT NULL,
  `cycl_nr` double unsigned DEFAULT NULL,
  `gren_nr` double unsigned DEFAULT NULL,
  `toll_nr` double unsigned DEFAULT NULL,
  `gcst_nr` double unsigned DEFAULT NULL,
  `shap` multilinestring NOT NULL,
  PRIMARY KEY (`idno`),
  KEY `tail` (`tail`),
  KEY `head` (`head`),
  KEY `dval` (`dval`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;