/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.36
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public enum debugLevel {
  MS_DEBUGLEVEL_ERRORSONLY = 0,
  MS_DEBUGLEVEL_DEBUG = 1,
  MS_DEBUGLEVEL_TUNING = 2,
  MS_DEBUGLEVEL_V = 3,
  MS_DEBUGLEVEL_VV = 4,
  MS_DEBUGLEVEL_VVV = 5
}
