/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.36
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public enum MS_BITMAP_FONT_SIZES {
  MS_TINY,
  MS_SMALL,
  MS_MEDIUM,
  MS_LARGE,
  MS_GIANT
}
