/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.36
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public enum MS_CONNECTION_TYPE {
  MS_INLINE,
  MS_SHAPEFILE,
  MS_TILED_SHAPEFILE,
  MS_SDE,
  MS_OGR,
  MS_UNUSED_1,
  MS_POSTGIS,
  MS_WMS,
  MS_ORACLESPATIAL,
  MS_WFS,
  MS_GRATICULE,
  MS_MYSQL,
  MS_RASTER,
  MS_PLUGIN,
  MS_UNION
}
