/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.36
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public enum MS_CAPS_JOINS_AND_CORNERS {
  MS_CJC_NONE,
  MS_CJC_BEVEL,
  MS_CJC_BUTT,
  MS_CJC_MITER,
  MS_CJC_ROUND,
  MS_CJC_SQUARE,
  MS_CJC_TRIANGLE
}
