/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.36
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public enum MS_GEOS_OPERATOR {
  MS_GEOS_EQUALS,
  MS_GEOS_DISJOINT,
  MS_GEOS_TOUCHES,
  MS_GEOS_OVERLAPS,
  MS_GEOS_CROSSES,
  MS_GEOS_INTERSECTS,
  MS_GEOS_WITHIN,
  MS_GEOS_CONTAINS,
  MS_GEOS_BEYOND,
  MS_GEOS_DWITHIN
}
