/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.36
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public enum MS_IMAGEMODE {
  MS_IMAGEMODE_PC256,
  MS_IMAGEMODE_RGB,
  MS_IMAGEMODE_RGBA,
  MS_IMAGEMODE_INT16,
  MS_IMAGEMODE_FLOAT32,
  MS_IMAGEMODE_BYTE,
  MS_IMAGEMODE_FEATURE,
  MS_IMAGEMODE_NULL
}
