/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.36
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public enum MS_JOIN_CONNECTION_TYPE {
  MS_DB_XBASE,
  MS_DB_CSV,
  MS_DB_MYSQL,
  MS_DB_ORACLE,
  MS_DB_POSTGRES
}
