/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.36
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public enum MS_JOIN_TYPE {
  MS_JOIN_ONE_TO_ONE,
  MS_JOIN_ONE_TO_MANY
}
