/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.36
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public enum MS_LAYER_TYPE {
  MS_LAYER_POINT,
  MS_LAYER_LINE,
  MS_LAYER_POLYGON,
  MS_LAYER_RASTER,
  MS_LAYER_ANNOTATION,
  MS_LAYER_QUERY,
  MS_LAYER_CIRCLE,
  MS_LAYER_TILEINDEX,
  MS_LAYER_CHART
}
