/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.36
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public enum MS_LABEL_BINDING_ENUM {
  MS_LABEL_BINDING_SIZE,
  MS_LABEL_BINDING_ANGLE,
  MS_LABEL_BINDING_COLOR,
  MS_LABEL_BINDING_OUTLINECOLOR,
  MS_LABEL_BINDING_FONT,
  MS_LABEL_BINDING_PRIORITY,
  MS_LABEL_BINDING_POSITION,
  MS_LABEL_BINDING_SHADOWSIZEX,
  MS_LABEL_BINDING_SHADOWSIZEY
}
