/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.36
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public enum MS_POSITIONS_ENUM {
  MS_UL = 101,
  MS_LR,
  MS_UR,
  MS_LL,
  MS_CR,
  MS_CL,
  MS_UC,
  MS_LC,
  MS_CC,
  MS_AUTO,
  MS_XY,
  MS_FOLLOW,
  MS_NONE,
  MS_AUTO2
}
