/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.36
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public enum MS_PARSE_TYPE_ENUM {
  MS_PARSE_TYPE_BOOLEAN,
  MS_PARSE_TYPE_STRING,
  MS_PARSE_TYPE_SHAPE
}
