/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.36
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public enum MS_QUERY_TYPE {
  MS_QUERY_IS_NULL,
  MS_QUERY_BY_POINT,
  MS_QUERY_BY_RECT,
  MS_QUERY_BY_SHAPE,
  MS_QUERY_BY_ATTRIBUTE,
  MS_QUERY_BY_INDEX,
  MS_QUERY_BY_FILTER
}
