/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.36
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public enum MS_STYLE_BINDING_ENUM {
  MS_STYLE_BINDING_SIZE,
  MS_STYLE_BINDING_WIDTH,
  MS_STYLE_BINDING_ANGLE,
  MS_STYLE_BINDING_COLOR,
  MS_STYLE_BINDING_OUTLINECOLOR,
  MS_STYLE_BINDING_SYMBOL,
  MS_STYLE_BINDING_OUTLINEWIDTH,
  MS_STYLE_BINDING_OPACITY
}
