/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.36
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public enum MS_SYMBOL_TYPE {
  MS_SYMBOL_SIMPLE = 1000,
  MS_SYMBOL_VECTOR,
  MS_SYMBOL_ELLIPSE,
  MS_SYMBOL_PIXMAP,
  MS_SYMBOL_TRUETYPE,
  MS_SYMBOL_HATCH,
  MS_SYMBOL_SVG
}
