/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.36
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public enum MS_TOKEN_COMPARISON_ENUM {
  MS_TOKEN_COMPARISON_EQ = 120,
  MS_TOKEN_COMPARISON_NE,
  MS_TOKEN_COMPARISON_GT,
  MS_TOKEN_COMPARISON_LT,
  MS_TOKEN_COMPARISON_LE,
  MS_TOKEN_COMPARISON_GE,
  MS_TOKEN_COMPARISON_IEQ,
  MS_TOKEN_COMPARISON_RE,
  MS_TOKEN_COMPARISON_IRE,
  MS_TOKEN_COMPARISON_IN,
  MS_TOKEN_COMPARISON_LIKE,
  MS_TOKEN_COMPARISON_INTERSECTS,
  MS_TOKEN_COMPARISON_DISJOINT,
  MS_TOKEN_COMPARISON_TOUCHES,
  MS_TOKEN_COMPARISON_OVERLAPS,
  MS_TOKEN_COMPARISON_CROSSES,
  MS_TOKEN_COMPARISON_WITHIN,
  MS_TOKEN_COMPARISON_CONTAINS,
  MS_TOKEN_COMPARISON_BEYOND,
  MS_TOKEN_COMPARISON_DWITHIN
}
