/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.36
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public enum MS_TOKEN_FUNCTION_ENUM {
  MS_TOKEN_FUNCTION_LENGTH = 140,
  MS_TOKEN_FUNCTION_TOSTRING,
  MS_TOKEN_FUNCTION_COMMIFY,
  MS_TOKEN_FUNCTION_AREA,
  MS_TOKEN_FUNCTION_ROUND,
  MS_TOKEN_FUNCTION_FROMTEXT,
  MS_TOKEN_FUNCTION_BUFFER
}
