/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.36
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public enum MS_TOKEN_LITERAL_ENUM {
  MS_TOKEN_LITERAL_NUMBER = 110,
  MS_TOKEN_LITERAL_STRING,
  MS_TOKEN_LITERAL_TIME,
  MS_TOKEN_LITERAL_SHAPE
}
