/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.36
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public enum MS_TOKEN_LOGICAL_ENUM {
  MS_TOKEN_LOGICAL_AND = 100,
  MS_TOKEN_LOGICAL_OR,
  MS_TOKEN_LOGICAL_NOT
}
