/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.36
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public enum MS_UNITS {
  MS_INCHES,
  MS_FEET,
  MS_MILES,
  MS_METERS,
  MS_KILOMETERS,
  MS_DD,
  MS_PIXELS,
  MS_PERCENTAGES,
  MS_NAUTICALMILES
}
